# @name Variables
@local = http://127.0.0.1:8000
@remote = https://multitoolwebsite-kwr2.onrender.com
@host = {{remote}}

### Root Endpoint Testi
# API'nin ayakta olup olmadığını kontrol eder
GET {{host}}/
Accept: application/json

### AI Background Remover Testi
POST {{host}}/api/remove-bg
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_image.png"
Content-Type: image/png

< ./test_image.png
--boundary--

### OCR Reader Testi
POST {{host}}/api/ocr
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="document.png"
Content-Type: image/png

< ./document.png
--boundary--